#!/bin/sh

_sock="/tmp/firefox.sock"

if [ -S "${_sock}" ]
then
    if [ ${#} -eq 0 ]
    then
        printf 'nw' | nc -NU "${_sock}"
    else
        printf '%s' "nw$(printf '|%s' "${@}")" | nc -NU "${_sock}"
    fi
else
    if ! pgrep -f '/usr/lib/firefox/firefox' > /dev/null
    then
        exec /usr/lib/firefox/firefox "${@}"
    fi
fi
